---
Formação Cientista de Dados
Limpeza e Tratamento de Dados 
---
```{r}
# importar dados, string vazio como NA, string como fatores
filename <- "dados/Churn.csv"
dir <- getwd()
fullpath <- file.path(dir, filename)
dados = read.csv(fullpath, sep=";", na.strings = "", 
                 stringsAsFactors = T)
head(dados)
summary(dados)


```
Colunas
```{r}
# Dar nomes corretos as colunas
colnames(dados) =c("Id","Score","Estado","Genero","Idade","Patrimonio", "Saldo",
                   "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")
head(dados)
```
Explorar dados colunas categóricas
```{r}
#Estados
counts = table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados")
#Gêneros
counts = table(dados$Genero)
barplot(counts, main = "Gêneros", xlab = "Gêneros")
```
Explorar, colunas numéricas
```{r}
#Score
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```
Idade
```{r}
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
Saldo

```{r}
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```
Salário

```{r}
summary(dados$Salario)
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F)
```
Valores faltantes - NAs
```{r}
#valores faltantes NAs
dados[!complete.cases(dados),]
```
Salários
```{r}
#tratar salários
summary(dados$Salario)
#ver mediana
median(dados$Salario, na.rm = T)
#atribuir mediana a NAs
dados[is.na(dados$Salario),]$Salario = median(dados$Salario, na.rm = T)
#Buscar NAs em salario para checar
dados[!complete.cases(dados$Salario),]
```
Falta de padronização em Gênero
```{r}
unique(dados$Genero)
summary(dados$Genero)
#trasformar F e Fem em Feminino
#trasformar M em Masculino (moda)
dados[is.na(dados$Genero) | dados$Genero == "M",]$Genero = "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem",]$Genero = "Feminino"
#Ver resultado
summary(dados$Genero)
#remover levels não utilizados
dados$Genero = factor(dados$Genero)
#visualizar novamente
summary(dados$Genero)
```
Idades fora do dominio
```{r}
summary(dados$Idade)
#fora do domino, numérico - ver idades anormais
dados[dados$Idade < 0 | dados$Idades> 110,]$Idade
#não temos idade NAs
dados[is.na(dados$Idade),]
#opção, preencher com mediana
median(dados$Idade)
#substituição
dados[dados$Idade < 0 | dados$Idade > 110,]$Idade = median(dados$Idade)
#buscamos novamente idade anormais
dados[dados$Idade < 0 | dados$Idade > 110,]
summary(dados$Idade)
```
Dados duplicados
```{r}
#buscar duplicados pelo ID
x = dados[duplicated(dados$Id),]
x
#Verificamos que o ID 81 está duplicado
#vamos excluir pelo ID não indice
dados = dados[-c(82),]
# Verificamos novamente duplicados
x = dados[duplicated(dados$Id),]
x
```
Estado fora do domínio
```{r}
unique(dados$Estado)
summary(dados$Estado)
#preencher com a moda RS
dados[!dados$Estado %in% c("RS","SC","PR"),]$Estado ="RS"
summary(dados$Estado)
#removemos fatores não usados
dados$Estado = factor(dados$Estado)
#visualizar novamente
summary(dados$Estado)
```
Outliers
```{r}
#outliers, criando um parametro com desvio padrão
desv = sd(dados$Salario, na.rm = T)
dados[dados$Salario >= 2 *desv ,]$Salario
#outra forma semelhante mas sem os NAs
boxplot(dados$Salario)
x = boxplot(dados$Salario)$out
x
#atualizar todos para mediana
median(dados$Salario)
dados[dados$Salario >= 2 * desv,]$Salario = median(dados$Salario)
#checamos se sairam os outliers
dados[dados$Salario >= 2 * desv,]$Salario
```

